### ISSUE TITLE
Allow custom CSS classes

### ISSUE THREAD

**Issue by stefan-niedermann** [mibuthu/wp-link-view#19]
Please allow to add custom CSS classes to the ul.lv-link-list Node.
1. While using shortcode OR
2. As a general Option in the settings.
Thank you!

**Comment by mibuthu** [comment]
There is a general option available to add CSS for Link View

**Comment by stefan-niedermann** [comment]
Well, the issue is to add **classes** to the ListView. this would allow to use a generic style sheet for hard coded lists *and* LinkView-generated lists without the need of duplicate code.

**Comment by mibuthu** [comment]
But there are already special classes for every displayed elements included?! Additionally you can add a class suffix (see shortcode attribute "class_suffix") to allow different css classes for different link-view shortcodes.

**Comment by stefan-niedermann** [comment]
I will try to explain:

i developed a custom wordpress theme. some lists (with class "colored") are styled specially.
The Problem is, that i have "static" lists - for example in posts or even hardcoded, and on the other hand i have lists which are dynamically generated by LinkView.

So - now i have the choice to style these lists, too:

1.) I use the custom css option. This means i have to duplicate all the code related to "colored"-lists. If i'm doing changes in my template-style, i will have to do it again in the LinkView-Stylesheets.
```css
/* My Template Stylesheet */
ul.colored {
    /* List Styling */
}
```
```css
/* Custom CSS provided by LinkView-Plugin */
ul.colored {
    /* Same List Styling as in Template Style */
}
```

2.) I'm doing it like this to save duplicate code:
```css
ul.colored, ul.lv-link-list {
    /* List Styling */
}
```
But this means, my template is now Plug-In-Dependend. I do not want this.

3.) This i what i want to do:
```css
/* My Template Stylesheet */
ul.colored {
    /* List Styling */
}
```
Then: Adding to LinkView-Plugin ul-node automatically the class "colored" (or any other i want), so it gets automatically styled by the ul.colored in my Template Stylesheet.

I hope this helps to explain.

Thank you very much & Best regards

**Comment by mibuthu** [comment]
Thanks for the info, now I know what you want to have. I think this is difficult to implement but I will have a look on it.

**Comment by mibuthu** [comment]
I have added some more options to add custom classes in version 0.8.0.
Probably this solves your issue, at least partly.
