### ISSUE TITLE
Need any help?

### ISSUE THREAD

**Issue by andrewshell** [mibuthu/wp-link-view#37]
Hi, I'm the developer of the [Nofollow Links](https://wordpress.org/plugins/nofollow-links/) plugin. Looks like you have some items you'd like to accomplish in your list of issues.

I'd be happy to help out if you're interested. I started looking at your code because I found that there was a compatibility issue between our plugins.

Please let me know if there is anything specifically you'd like me to take a look at.

**Comment by mibuthu** [comment]
I have merged your pull request.
